### ISSUE TITLE
Tag/Release

### ISSUE THREAD

**Issue by reiz** [jeromeetienne/virtualjoystick.js#10]
Hi. Somebody submitted this project at VersionEye to track it. Unfortunately we can't, because there are no releases/versions. Would be awesome if you would release officially the first version and create a git tag for that. 
Many Thanks.

**Comment by jeromeetienne** [comment]
done https://github.com/jeromeetienne/virtualjoystick.js/tree/v1.0

thanks for noticing. btw what is versioneye ?

**Comment by reiz** [comment]
Many Thanks! VersionEye tracks open source libraries and notifies followers about new versions. Here is your project on VersionEye: http://www.versioneye.com/javascript/jeromeetienne:virtualjoystick.js/v1.0.
