### ISSUE TITLE
Lock joystick base in a specific place

### ISSUE THREAD

**Issue by Forzaferrarileo** [jeromeetienne/virtualjoystick.js#12]
I tried setting the position from absolute to fixed , but it doesn't work . there's a way to do that?

**Comment by jeromeetienne** [comment]
i dunno. i never tried

**Comment by erichlof** [comment]
@Forzaferrarileo and @jeromeetienne ,

Referencing this issue:
https://github.com/jeromeetienne/virtualjoystick.js/issues/13

**Comment by jeromeetienne** [comment]
@Forzaferrarileo it is now possible thanks to @erichlof. see the stationary base example
