### ISSUE TITLE
add a fire button

### ISSUE THREAD

**Issue by jeromeetienne** [jeromeetienne/virtualjoystick.js#2]
- on the left of the screen it is the stick to control direction
- on the right, it is the fire

**Comment by ghost** [comment]
Hello I Am interested by your work, I have developed Mario Bros in Javascript and I want to play this on the touch screen. But I need a fire button with the stick to jump.
I don't know how doing this, because the navigator on my Transformer Pad don't accept multi touch.

**Comment by jeromeetienne** [comment]
You are trying to emulate multi touch on a single touch device... not easy :)

maybe you can play with timers... like if you press for a short time and dont drag, it is fire... else it is moving. but it wont be much reliable. and players may become frustrated. 

i dunno any good solution to that really

**Comment by ghost** [comment]
Hello, I try this and it work. I have a fire button with your joystick :)

http://www.html5rocks.com/en/mobile/touch.html

2012/2/10 Jerome Etienne <
reply@reply.github.com

**Comment by jeromeetienne** [comment]
Good:)
